get_one_index_1: |-
  client.getIndex('movie').show()
list_all_indexes_1: |-
  client.listIndexes()
create_an_index_1: |-
  client.createIndex({ uid: 'movie' })
update_an_index_1: |-
  client.updateIndex({ uid: 'movie' })
delete_an_index_1: |-
  client.getIndex('movie').deleteIndex()
get_one_document_1: |-
get_documents_1: |-
add_or_replace_documents_1: |-
add_or_update_documents_1: |-
delete_all_documents_1: |-
delete_one_document_1: |-
delete_documents_1: |-
search_1: |-
get_update_1: |-
get_all_updates_1: |-
get_keys: |-
get_settings_1: |-
update_settings_1: |-
reset_settings_1: |-
get_synonyms_1: |-
update_synonyms_1: |-
reset_synonyms_1: |-
get_stop_words_1: |-
update_stop_words_1: |-
reset_stop_words_1: |-
get_ranking_rules_1: |-
update_ranking_rules_1: |-
reset_ranking_rules_1: |-
get_distinct_attribute_1: |-
update_distinct_attribute_1: |-
reset_distinct_attribute_1: |-
get_searchable_attributes_1: |-
update_searchable_attributes_1: |-
reset_searchable_attributes_1: |-
get_displayed_attributes_1: |-
update_displayed_attributes_1: |-
reset_displayed_attributes_1: |-
get_accept_new_fields_1: |-
update_accept_new_fields_1: |-
get_index_stats_1: |-
get_indexes_stats_1: |-
get_health_1: |-
update_health_1: |-
get_version_1: |-
get_pretty_sys_info_1: |-
get_sys_info_1: |-
