type CamelToSnakeCase<S extends string> = S extends `${infer T}${infer U}`
  ? `${T extends Capitalize<T> ? "_" : ""}${Lowercase<T>}${CamelToSnakeCase<U>}`
  : S;
type PascalToSnakeCase<S extends string> = CamelToSnakeCase<Uncapitalize<S>>;

/**
 * {@link https://www.meilisearch.com/docs/reference/errors/error_codes}
 *
 * @see `meilisearch_types::error::Code`
 */
export type Code = PascalToSnakeCase<
  | "ApiKeyAlreadyExists"
  | "ApiKeyNotFound"
  | "BadParameter"
  | "BadRequest"
  | "DatabaseSizeLimitReached"
  | "DocumentNotFound"
  | "DumpAlreadyProcessing"
  | "DumpNotFound"
  | "DumpProcessFailed"
  | "DuplicateIndexFound"
  | "ImmutableApiKeyActions"
  | "ImmutableApiKeyCreatedAt"
  | "ImmutableApiKeyExpiresAt"
  | "ImmutableApiKeyIndexes"
  | "ImmutableApiKeyKey"
  | "ImmutableApiKeyUid"
  | "ImmutableApiKeyUpdatedAt"
  | "ImmutableIndexCreatedAt"
  | "ImmutableIndexUid"
  | "ImmutableIndexUpdatedAt"
  | "IndexAlreadyExists"
  | "IndexCreationFailed"
  | "IndexNotFound"
  | "IndexPrimaryKeyAlreadyExists"
  | "IndexPrimaryKeyMultipleCandidatesFound"
  | "IndexPrimaryKeyNoCandidateFound"
  | "Internal"
  | "InvalidApiKey"
  | "InvalidApiKeyActions"
  | "InvalidApiKeyDescription"
  | "InvalidApiKeyExpiresAt"
  | "InvalidApiKeyIndexes"
  | "InvalidApiKeyLimit"
  | "InvalidApiKeyName"
  | "InvalidApiKeyOffset"
  | "InvalidApiKeyUid"
  | "InvalidContentType"
  | "InvalidDocumentCsvDelimiter"
  | "InvalidDocumentFields"
  | "InvalidDocumentRetrieveVectors"
  | "MissingDocumentFilter"
  | "MissingDocumentEditionFunction"
  | "InvalidDocumentFilter"
  | "InvalidDocumentGeoField"
  | "InvalidVectorDimensions"
  | "InvalidVectorsType"
  | "InvalidDocumentId"
  | "InvalidDocumentIds"
  | "InvalidDocumentLimit"
  | "InvalidDocumentOffset"
  | "InvalidSearchEmbedder"
  | "InvalidSimilarEmbedder"
  | "InvalidSearchHybridQuery"
  | "InvalidIndexLimit"
  | "InvalidIndexOffset"
  | "InvalidIndexPrimaryKey"
  | "InvalidIndexUid"
  | "InvalidMultiSearchFacets"
  | "InvalidMultiSearchFacetsByIndex"
  | "InvalidMultiSearchFacetOrder"
  | "InvalidMultiSearchFederated"
  | "InvalidMultiSearchFederationOptions"
  | "InvalidMultiSearchMaxValuesPerFacet"
  | "InvalidMultiSearchMergeFacets"
  | "InvalidMultiSearchQueryFacets"
  | "InvalidMultiSearchQueryPagination"
  | "InvalidMultiSearchQueryRankingRules"
  | "InvalidMultiSearchQueryPosition"
  | "InvalidMultiSearchRemote"
  | "InvalidMultiSearchWeight"
  | "InvalidNetworkRemotes"
  | "InvalidNetworkSelf"
  | "InvalidNetworkSearchApiKey"
  | "InvalidNetworkUrl"
  | "InvalidSearchAttributesToSearchOn"
  | "InvalidSearchAttributesToCrop"
  | "InvalidSearchAttributesToHighlight"
  | "InvalidSimilarAttributesToRetrieve"
  | "InvalidSimilarRetrieveVectors"
  | "InvalidSearchAttributesToRetrieve"
  | "InvalidSearchRankingScoreThreshold"
  | "InvalidSimilarRankingScoreThreshold"
  | "InvalidSearchRetrieveVectors"
  | "InvalidSearchCropLength"
  | "InvalidSearchCropMarker"
  | "InvalidSearchFacets"
  | "InvalidSearchSemanticRatio"
  | "InvalidSearchLocales"
  | "InvalidFacetSearchExhaustiveFacetCount"
  | "InvalidFacetSearchFacetName"
  | "InvalidSimilarId"
  | "InvalidSearchFilter"
  | "InvalidSimilarFilter"
  | "InvalidSearchHighlightPostTag"
  | "InvalidSearchHighlightPreTag"
  | "InvalidSearchHitsPerPage"
  | "InvalidSimilarLimit"
  | "InvalidSearchLimit"
  | "InvalidSearchMatchingStrategy"
  | "InvalidSimilarOffset"
  | "InvalidSearchOffset"
  | "InvalidSearchPage"
  | "InvalidSearchQ"
  | "InvalidFacetSearchQuery"
  | "InvalidFacetSearchName"
  | "FacetSearchDisabled"
  | "InvalidSearchVector"
  | "InvalidSearchShowMatchesPosition"
  | "InvalidSearchShowRankingScore"
  | "InvalidSimilarShowRankingScore"
  | "InvalidSearchShowRankingScoreDetails"
  | "InvalidSimilarShowRankingScoreDetails"
  | "InvalidSearchSort"
  | "InvalidSearchDistinct"
  | "InvalidSettingsDisplayedAttributes"
  | "InvalidSettingsDistinctAttribute"
  | "InvalidSettingsProximityPrecision"
  | "InvalidSettingsFacetSearch"
  | "InvalidSettingsPrefixSearch"
  | "InvalidSettingsFaceting"
  | "InvalidSettingsFilterableAttributes"
  | "InvalidSettingsPagination"
  | "InvalidSettingsSearchCutoffMs"
  | "InvalidSettingsEmbedders"
  | "InvalidSettingsRankingRules"
  | "InvalidSettingsSearchableAttributes"
  | "InvalidSettingsSortableAttributes"
  | "InvalidSettingsStopWords"
  | "InvalidSettingsNonSeparatorTokens"
  | "InvalidSettingsSeparatorTokens"
  | "InvalidSettingsDictionary"
  | "InvalidSettingsSynonyms"
  | "InvalidSettingsTypoTolerance"
  | "InvalidSettingsLocalizedAttributes"
  | "InvalidState"
  | "InvalidStoreFile"
  | "InvalidSwapDuplicateIndexFound"
  | "InvalidSwapIndexes"
  | "InvalidTaskAfterEnqueuedAt"
  | "InvalidTaskAfterFinishedAt"
  | "InvalidTaskAfterStartedAt"
  | "InvalidTaskBeforeEnqueuedAt"
  | "InvalidTaskBeforeFinishedAt"
  | "InvalidTaskBeforeStartedAt"
  | "InvalidTaskCanceledBy"
  | "InvalidTaskFrom"
  | "InvalidTaskLimit"
  | "InvalidTaskReverse"
  | "InvalidTaskStatuses"
  | "InvalidTaskTypes"
  | "InvalidTaskUids"
  | "InvalidBatchUids"
  | "IoError"
  | "FeatureNotEnabled"
  | "MalformedPayload"
  | "MaxFieldsLimitExceeded"
  | "MissingApiKeyActions"
  | "MissingApiKeyExpiresAt"
  | "MissingApiKeyIndexes"
  | "MissingAuthorizationHeader"
  | "MissingContentType"
  | "MissingDocumentId"
  | "MissingFacetSearchFacetName"
  | "MissingIndexUid"
  | "MissingMasterKey"
  | "MissingNetworkUrl"
  | "MissingPayload"
  | "MissingSearchHybrid"
  | "MissingSwapIndexes"
  | "MissingTaskFilters"
  | "NoSpaceLeftOnDevice"
  | "PayloadTooLarge"
  | "RemoteBadResponse"
  | "RemoteBadRequest"
  | "RemoteCouldNotSendRequest"
  | "RemoteInvalidApiKey"
  | "RemoteRemoteError"
  | "RemoteTimeout"
  | "TooManySearchRequests"
  | "TaskNotFound"
  | "TaskFileNotFound"
  | "BatchNotFound"
  | "TooManyOpenFiles"
  | "TooManyVectors"
  | "UnretrievableDocument"
  | "UnretrievableErrorCode"
  | "UnsupportedMediaType"
  | "VectorEmbeddingError"
  | "NotFoundSimilarId"
  | "InvalidDocumentEditionContext"
  | "InvalidDocumentEditionFunctionFilter"
  | "EditDocumentsByFunctionError"
>;

/**
 * {@link https://www.meilisearch.com/docs/reference/errors/overview#errors}
 *
 * @see `meilisearch_types::error::ErrorType`
 */
export type ErrorType = PascalToSnakeCase<
  "Internal" | "InvalidRequest" | "Auth" | "System"
>;

/**
 * {@link https://www.meilisearch.com/docs/reference/errors/overview#error-format}
 *
 * @see `meilisearch_types::error::ResponseError`
 */
export type ResponseError = {
  message: string;
  code: Code;
  type: ErrorType;
  link: string;
};
