name: Create Version Bump PR
on:
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Bump version in package files and create PR
        uses: ./.github/actions/bump-version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
