name: "Set up Node.js"
inputs:
  node-version:
    default: "lts/*"
  registry-url:
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: "npm"
    - name: Install dependencies
      shell: bash
      run: npm install
